# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY port_scanning_attack_v3.py .

# Install any required packages (none needed for this basic script)

# Set the command to run the script
ENTRYPOINT ["python", "-u" ,"port_scanning_attack_v3.py"]